name: Html5-QRCode

env:
  NODE_VERSION: '16.x'

on:
  pull_request:
  push: 
    branches: 
      - master

jobs:
  all:
    name: Analyze, Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Node.js (${{ env.NODE_VERSION }})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Linter all files
        run: npm run lint

      - name: Run unit tests
        run: npm test

      - name: Build apps
        run: npm run build
